name: Container Registry

on:
  push:
    branches: [main]
    paths: [Dockerfile]
  pull_request:
    branches: [main]
    paths: [Dockerfile]
  schedule:
    # Once a week
    - cron: "0 0 * * */7"
  workflow_dispatch:

jobs:
  build-base:
    name: Build Base Image
    # aarch64 builds fail on ubuntu-24.04
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Build
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile
          pull: true
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          tags: ghcr.io/adley-nastri/flatter/flatter-base:latest

  build:
    name: Build
    needs: [build-base]
    # aarch64 builds fail on ubuntu-24.04
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        runtime:

          # KDE
          #
          # These are images for the KDE runtime. The maintainer doesn't use
          # these, but feel free to open a PR if out-of-date.
    
          - name: kde
            tag: 6.5
            flathub: >
              org.kde.Platform/x86_64/6.5
              org.kde.Sdk/x86_64/6.5
      fail-fast: false

    steps:
      - name: Cleanup
        run: |
          sudo rm -rf /opt/ghc \
                      /opt/hostedtoolcache/CodeQL \
                      /usr/share/dotnet \
                      /usr/local/lib/android
          sudo docker image prune --all --force
          sudo docker builder prune -a

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Generate Dockerfile
        run: |

          if [ -n "${{ matrix.runtime.flathub_beta }}" ]; then
          cat >> ${{ matrix.runtime.name }}.Dockerfile << EOF
          RUN --security=insecure flatpak install -y --noninteractive \
                                          flathub-beta \
                                          ${{ matrix.runtime.flathub_beta }}
          EOF
          fi

          if [ -n "${{ matrix.runtime.flathub }}" ]; then
          cat >> ${{ matrix.runtime.name }}.Dockerfile << EOF
          RUN --security=insecure flatpak install -y --noninteractive \
                                          flathub \
                                          ${{ matrix.runtime.flathub }}
          EOF
          fi

      - name: Build
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          allow: security.insecure
          context: .
          file: ${{ matrix.runtime.name }}.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          tags: ghcr.io/${{ github.repository }}/${{ matrix.runtime.name }}:${{ matrix.runtime.tag }}
