name: Test

on:
  push:
    branches: [main]

jobs:
  flatter:
    name: Flatter
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/andyholmes/flatter/gnome:43
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup GPG
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build
        uses: andyholmes/actions/flatter@main
        with:
          manifests: |
            tests/manifests/ca.andyholmes.Test1.json
            tests/manifests/ca.andyholmes.Test2.yml
          gpg-sign: ${{ steps.gpg.outputs.fingerprint }}
          bundle-artifact: true
          pages-artifact: true

